# Generated by Django 5.0.1 on 2024-02-04 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cred', models.IntegerField(default=1)),
                ('cataloge', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Edu | Course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Edu | Departments',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Core | Events',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('requierd_credit', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Edu | Majors',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home')], default='Mobile', max_length=6)),
            ],
            options={
                'verbose_name': 'PhoneNumber',
                'verbose_name_plural': 'Core | PhoneNumbers',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Sat', 'Saturday'), ('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Edu | Terms',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.course')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Edu | Class',
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='core.course')),
                ('prerequisites', models.ManyToManyField(related_name='pre_req', to='core.course')),
            ],
            options={
                'verbose_name': 'Prerequisite',
                'verbose_name_plural': 'Edu | Prerequisites',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('project', 'Project')], max_length=25)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.class')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_course', to='core.event')),
            ],
            options={
                'verbose_name': 'ClassEvent',
                'verbose_name_plural': 'Core | ClassEvents',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major'),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=10)),
                ('courses', models.ManyToManyField(related_name='chart', to='core.course')),
                ('major', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.major')),
            ],
            options={
                'verbose_name': 'Chart',
                'verbose_name_plural': 'Edu | Charts',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Instructor', 'Instructor'), ('Assistant Professor', 'Assistant Professor'), ('Associative Professor', 'Associative Professor'), ('Full Professor', 'Full Professor')], max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Users | Professors',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='intructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.professor'),
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=15, unique=True)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor', to='core.professor')),
            ],
            options={
                'verbose_name': 'Advisor',
                'verbose_name_plural': 'Users | AdvisorProfessors',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.ManyToManyField(to='core.schedule'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=15, unique=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.advisor')),
                ('entery_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.term')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Users | Students',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
            options={
                'verbose_name': 'Enrolls',
                'verbose_name_plural': 'Users | StudentEnrollment',
            },
        ),
        migrations.CreateModel(
            name='AdvisingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(choices=[('s', 'Student'), ('a', 'Advisor')], max_length=10)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.advisor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.student')),
            ],
            options={
                'verbose_name': 'Core',
                'verbose_name_plural': 'Core | AdvisingMessages',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.term'),
        ),
        migrations.CreateModel(
            name='TermEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('preregister', 'preregister'), ('term', 'Term'), ('class', 'Class'), ('register', 'Register'), ('adjustment', 'Adjustment'), ('drop', 'Drop'), ('exams', 'Exams')], max_length=25)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term_event', to='core.event')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.term')),
            ],
            options={
                'verbose_name': 'TermEvent',
                'verbose_name_plural': 'Core | TermEvents',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=1000)),
                ('degree', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=10, null=True)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.major')),
                ('phone_numbers', models.ManyToManyField(blank=True, to='core.phonenumber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserAccount',
                'verbose_name_plural': 'Core | UserAccounts',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.useraccount'),
        ),
        migrations.AddField(
            model_name='professor',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='core.useraccount'),
        ),
    ]
