# Generated by Django 5.0.1 on 2024-02-01 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cred', models.IntegerField(default=1)),
                ('cataloge', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('requierd_credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home')], default='Mobile', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Sat', 'Saturday'), ('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('numerical_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('schedule', models.ManyToManyField(to='core.schedule')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.term')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='core.course')),
                ('prerequisites', models.ManyToManyField(related_name='pre_req', to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.CreateModel(
            name='EducationalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('degree', models.CharField(max_length=255)),
                ('avg_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('institution_name', models.CharField(max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.major')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.major'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.useraccount')),
                ('rank', models.CharField(choices=[('Instructor', 'Instructor'), ('Assistant Professor', 'Assistant Professor'), ('Associative Professor', 'Associative Professor'), ('Full Professor', 'Full Professor')], max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'verbose_name': 'professor',
            },
            bases=('core.useraccount',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.useraccount')),
                ('student_id', models.CharField(max_length=15, unique=True)),
            ],
            bases=('core.useraccount',),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='educational_stat',
            field=models.ManyToManyField(blank=True, to='core.educationalstat'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, to='core.phonenumber'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('name', models.CharField(choices=[('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('project', 'Project')], max_length=25)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.class')),
            ],
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='TermEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('name', models.CharField(choices=[('preregister', 'preregister'), ('term', 'Term'), ('class', 'Class'), ('register', 'Register'), ('adjustment', 'Adjustment'), ('drop', 'Drop'), ('exams', 'Exams')], max_length=25)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.term')),
            ],
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('professor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.professor')),
                ('advisor_id', models.CharField(max_length=15, unique=True)),
            ],
            bases=('core.professor',),
        ),
        migrations.AddField(
            model_name='class',
            name='intructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.advisor'),
        ),
        migrations.CreateModel(
            name='AdvisingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advisor')),
            ],
        ),
    ]
