# Generated by Django 5.0.1 on 2024-02-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisingmessage',
            name='sender',
            field=models.CharField(choices=[('advisor', 'student'), ('advisor', 'advisor')], max_length=10),
        ),
    ]
