# Generated by Django 5.0.1 on 2024-02-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_advisingmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisingmessage',
            name='sender',
            field=models.CharField(choices=[('student', 'Student'), ('advisor', 'Advisor')], max_length=10),
        ),
    ]
