# Generated by Django 5.0.1 on 2024-02-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_advisingmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, to='core.schedule'),
        ),
    ]
